name: Alerts to Discord

on:
  push:
    branches: ["main"]   # mude para ["**"] se quiser alertar qualquer branch
  pull_request:
    types: [closed]

jobs:
  notify:
    # push no main OU PR fechado que foi mergeado
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    env:
      WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
      REPO: ${{ github.repository }}
      ACTOR: ${{ github.actor }}
      RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      REF_NAME: ${{ github.ref_name }}
      COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
      COMMIT_MSG: ${{ github.event.head_commit.message }}
      PR_TITLE: ${{ github.event.pull_request.title }}
      PR_URL: ${{ github.event.pull_request.html_url }}

    steps:
      - name: Enviar alerta ao Discord
        uses: actions/github-script@v7
        with:
          script: |
            if (!process.env.WEBHOOK) {
              core.setFailed("Secret DISCORD_WEBHOOK_URL ausente.");
              return;
            }
            const isPush = process.env.GITHUB_EVENT_NAME === 'push';
            const text = isPush
              ? `[commit] repo=${process.env.REPO} branch=${process.env.REF_NAME} actor=${process.env.ACTOR} msg='${(process.env.COMMIT_MSG||'').replace(/\n/g,' ')}' → ${process.env.COMMIT_URL} | run ${process.env.RUN_URL}`
              : `[merge]  repo=${process.env.REPO} branch=main actor=${process.env.ACTOR} title='${(process.env.PR_TITLE||'').replace(/\n/g,' ')}' → ${process.env.PR_URL} | run ${process.env.RUN_URL}`;

            const res = await fetch(process.env.WEBHOOK, {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({ content: text })
            });

            core.info(`Discord status: ${res.status}`);
            if (!res.ok) core.setFailed(`Falha ao enviar para Discord: ${res.status}`);
